#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ejs from 'ejs';

import { loadSettings } from './load-settings.js';
import { loadGithubPosts } from './load-github-posts.js';
import { renderBody } from './parse-markdown.js';
import { validateContent, printWarnings } from './validate-content.js';
import { applyCrossSiteUtm } from './ga4-url-builder.js';
import { loadAdminPosts } from './load-admin-posts.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..', '..');
const VIEWS_DIR = path.join(PROJECT_ROOT, 'src', 'views');
const CACHE_DIR = path.join(PROJECT_ROOT, '.cache');
const DATA_DIR = path.join(CACHE_DIR, 'data');
const PAGES_DIR = path.join(CACHE_DIR, 'pages');
const ASSETS_DIR = path.join(PAGES_DIR, '_assets');

const ENTRY_JS = `// generated by build-github.js
import '../../../src/js/main.js';
`;

function parseMode(argv) {
  const flag = argv.find((a) => a.startsWith('--mode='));
  if (!flag) return 'dev';
  return flag.split('=')[1] || 'dev';
}

const rel = (p) => path.relative(PROJECT_ROOT, p).split(path.sep).join('/');

async function writeJson(file, data, outputs) {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, JSON.stringify(data, null, 2), 'utf-8');
  if (outputs) outputs.push(rel(file));
}

async function writeText(file, content, outputs) {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, content, 'utf-8');
  if (outputs) outputs.push(rel(file));
}

// Phase 5-b：渲染 SEO partials 後 post-process 注入 base.ejs 產出的 HTML 之 head 內。
// 採用 post-process 而非修改 base.ejs，避開未授權檔案修改。
// Phase 5-d：擴充加入 tracking/ga4 partial，邏輯一致。
const HEAD_PARTIALS = [
  { dir: 'seo', name: 'meta-tags' },
  { dir: 'seo', name: 'open-graph' },
  { dir: 'seo', name: 'canonical' },
  { dir: 'seo', name: 'json-ld' },
  { dir: 'tracking', name: 'ga4' },
  { dir: 'ads', name: 'adsense-head' },
];

async function renderHeadPartials(data) {
  const parts = [];
  for (const { dir, name } of HEAD_PARTIALS) {
    const html = await ejs.renderFile(
      path.join(VIEWS_DIR, dir, `${name}.ejs`),
      data,
      { async: true },
    );
    const trimmed = html.trim();
    if (trimmed) parts.push(trimmed);
  }
  return parts.join('\n');
}

async function renderPage({ template, data }) {
  const inner = await ejs.renderFile(path.join(VIEWS_DIR, template), data, { async: true });
  const wrapped = await ejs.renderFile(
    path.join(VIEWS_DIR, 'layout', 'base.ejs'),
    { ...data, body: inner },
    { async: true },
  );
  const headPartials = await renderHeadPartials(data);
  if (!headPartials) return wrapped;
  return wrapped.replace('</head>', `    ${headPartials.replace(/\n/g, '\n    ')}\n  </head>`);
}

function makeBaseData(settings) {
  const basePath = siteBasePath(settings);
  return (extra) => ({
    site: settings.site,
    navigation: settings.navigation,
    ga4: settings.ga4,
    ads: settings.ads,
    basePath,
    ...extra,
  });
}

// ---- 5-b SEO helpers --------------------------------------------------------

function siteBaseUrl(settings) {
  return (settings.site?.githubSiteUrl || '').replace(/\/+$/, '');
}

// Phase 10-e-fix-a：derive in-site base path from githubSiteUrl for project-site deploy.
//   user site (e.g. https://babel-lab.github.io)         → ''
//   project site (e.g. https://babel-lab.github.io/blog)  → '/blog'
//   consumed by EJS as <%= basePath %>{root-relative href} for internal navigation
function siteBasePath(settings) {
  const url = settings.site?.githubSiteUrl || '';
  if (!url) return '';
  try {
    return new URL(url).pathname.replace(/\/+$/, '');
  } catch (e) {
    return '';
  }
}

function ogLocaleFromLanguage(language) {
  if (language === 'zh-Hant') return 'zh_TW';
  if (language === 'zh-Hans') return 'zh_CN';
  if (language === 'en' || language === 'en-US') return 'en_US';
  return language || null;
}

function absolutizeUrl(url, base) {
  if (!url) return null;
  if (/^https?:\/\//.test(url)) return url;
  if (!base) return null;
  const cleanPath = url.replace(/^\/+/, '');
  return `${base}/${cleanPath}`;
}

function findCategoryName(settings, value) {
  if (!value) return null;
  const list = settings.categories || [];
  const cat = list.find((c) => c.id === value || c.slug === value);
  return cat?.name || value;
}

function buildCanonicalUrl({ pageType, post, slug, settings }) {
  const base = siteBaseUrl(settings);
  if (!base) return null;
  switch (pageType) {
    case 'home':
      return `${base}/`;
    case 'post-list':
      return `${base}/posts/`;
    case 'post-detail': {
      const raw = post?.canonical;
      if (raw && raw !== 'auto' && /^https?:\/\//.test(raw)) return raw;
      // Phase 9-i-f-b：cross-source mirror page → Blogger publishedUrl as canonical
      //   per docs/phase-9h-known-blockers.md §3（Blocker #1）
      //   對稱於 build-blogger.js 之 Phase 9-i-b2 修正
      if (post?.primaryPlatform === 'blogger') {
        const bloggerPublishedUrl = post.publish?.blogger?.publishedUrl;
        if (typeof bloggerPublishedUrl === 'string' && bloggerPublishedUrl !== '') {
          return bloggerPublishedUrl;
        }
      }
      return `${base}/posts/${post.slug}/`;
    }
    case 'category-list':
      return `${base}/categories/`;
    case 'category':
      return `${base}/categories/${slug}/`;
    case 'tag-list':
      return `${base}/tags/`;
    case 'tag':
      return `${base}/tags/${slug}/`;
    case '404':
    case 'design-system':
      return null;
    default:
      return null;
  }
}

function commonSeo({ pageType, settings, canonicalUrl }) {
  return {
    pageType,
    canonicalUrl,
    robots: 'index, follow',
    ogType: 'website',
    ogLocale: ogLocaleFromLanguage(settings.site?.language),
    ogImage: null,
    ogImageAlt: null,
    jsonLd: null,
    publishedTime: null,
    modifiedTime: null,
    keywords: null,
  };
}

function buildSeoForHome({ settings }) {
  const canonicalUrl = buildCanonicalUrl({ pageType: 'home', settings });
  const seo = commonSeo({ pageType: 'home', settings, canonicalUrl });
  if (canonicalUrl) {
    seo.jsonLd = {
      '@context': 'https://schema.org',
      '@type': 'WebSite',
      '@id': canonicalUrl,
      name: settings.site.siteName,
      url: canonicalUrl,
      description: settings.site.description,
      inLanguage: settings.site.language,
    };
  }
  return seo;
}

function buildSeoForPostList({ settings }) {
  const canonicalUrl = buildCanonicalUrl({ pageType: 'post-list', settings });
  return commonSeo({ pageType: 'post-list', settings, canonicalUrl });
}

// Phase 9-f-g-c: BlogPosting.mainEntity = Book（per docs/phase-9f-g-pre-plan.md §4-§5）
//   - 條件式：post.book object + (mediaType 缺省 OR === "book") + book.title non-empty
//   - 採 author fallback chain：authors[].displayName → localName → originalName → legacy book.author
//   - 不接 Periodical / DVD / YouTube / Netflix specific @type / library sameAs / @graph / Person.sameAs
//   - 與 build-blogger.js buildBloggerJsonLd() 兩端 mirror
function buildBookMainEntity(post) {
  const book = post.book;
  if (!book || typeof book !== 'object' || Array.isArray(book)) return null;
  if (book.mediaType && book.mediaType !== 'book') return null;
  if (typeof book.title !== 'string' || book.title.trim() === '') return null;
  const entity = { '@type': 'Book', name: book.title };
  // alternateName: non-empty titleEn / originalTitle; 1 → string；2 → array
  const altNames = [book.titleEn, book.originalTitle].filter(
    (v) => typeof v === 'string' && v.trim() !== '',
  );
  if (altNames.length === 1) entity.alternateName = altNames[0];
  else if (altNames.length > 1) entity.alternateName = altNames;
  // author: 優先 authors[] role 缺省或 === "author"；fallback chain name
  const authorPersons = (Array.isArray(book.authors) ? book.authors : [])
    .filter((a) => a && typeof a === 'object' && !Array.isArray(a))
    .filter((a) => !a.role || a.role === 'author')
    .map((a) => {
      const name = [a.displayName, a.localName, a.originalName].find(
        (v) => typeof v === 'string' && v.trim() !== '',
      );
      return name ? { '@type': 'Person', name } : null;
    })
    .filter(Boolean);
  if (authorPersons.length > 0) {
    entity.author = authorPersons;
  } else if (typeof book.author === 'string' && book.author.trim() !== '') {
    entity.author = [{ '@type': 'Person', name: book.author }];
  }
  // publisher: Organization
  if (typeof book.publisher === 'string' && book.publisher.trim() !== '') {
    entity.publisher = { '@type': 'Organization', name: book.publisher };
  }
  // datePublished: book.publishedYear → "YYYY"
  if (typeof book.publishedYear === 'number' && Number.isFinite(book.publishedYear)) {
    const year = Math.trunc(book.publishedYear);
    if (year >= 1000 && year <= 9999) entity.datePublished = String(year);
  }
  // isbn / image / bookEdition：non-empty 才出
  if (typeof book.isbn === 'string' && book.isbn.trim() !== '') entity.isbn = book.isbn;
  if (typeof book.coverImage === 'string' && book.coverImage.trim() !== '')
    entity.image = book.coverImage;
  if (typeof book.volumeLabel === 'string' && book.volumeLabel.trim() !== '')
    entity.bookEdition = book.volumeLabel;
  return entity;
}

function buildSeoForPostDetail({ settings, post }) {
  const canonicalUrl = buildCanonicalUrl({ pageType: 'post-detail', settings, post });
  const base = siteBaseUrl(settings);
  const ogImage = absolutizeUrl(post.cover, base);
  const seo = {
    ...commonSeo({ pageType: 'post-detail', settings, canonicalUrl }),
    ogType: 'article',
    ogImage,
    ogImageAlt: post.coverAlt || null,
    publishedTime: post.date || null,
    modifiedTime: post.updated || post.date || null,
    keywords: Array.isArray(post.tags) && post.tags.length > 0 ? post.tags : null,
  };
  // Phase 20260520-seo-2：robots meta precedence（per docs/seo-indexing-rules.md §3 / §6 SEO-2）
  //   優先序：
  //     1. post.seo.indexing (explicit；本批新增)
  //     2. contentKind === 'download' fallback (SEO-1；既有)
  //     3. default 'index, follow'（由 commonSeo spread 提供）
  //   非法 seo.indexing 值由 validate-content.js 之 invalid-seo-indexing 規則 (warning) 偵測；
  //   build 端對未匹配之值不主動 fallback，沿用 SEO-1 / default 行為
  const seoIndexing = post.seo && typeof post.seo.indexing === 'string' ? post.seo.indexing : null;
  if (seoIndexing === 'index') {
    seo.robots = 'index, follow';
  } else if (seoIndexing === 'noindex-follow') {
    seo.robots = 'noindex, follow';
  } else if (seoIndexing === 'noindex-nofollow') {
    seo.robots = 'noindex, nofollow';
  } else if (post.contentKind === 'download') {
    // Phase 20260520-seo-1 fallback：contentKind=download 視為導流漏斗後段頁
    //   - 保留 follow 以維持外向連結 PageRank flow（per docs/seo-indexing-rules.md §3 / §4）
    seo.robots = 'noindex, follow';
  }
  if (canonicalUrl) {
    // Phase 9-g-g-c: isPartOf 採最保守 site/blog 層級（per docs/phase-9g-g-pre-plan.md §5）
    //   - @type=Blog（schema.org 標準）；@id / url 依 post.primaryPlatform 指向對應平台 blog 首頁
    //   - 不使用 book / series / category 當 isPartOf（語義錯誤或當前無 ready post 觸發）
    //   - 與 build-blogger.js buildBloggerJsonLd() 兩端結構 mirror
    const blogSiteUrl =
      post.primaryPlatform === 'blogger'
        ? `${settings.site.bloggerSiteUrl}/`
        : `${settings.site.githubSiteUrl}/`;
    // Phase 9-g-g-d: mentions 接 relatedLinks + otherLinks（per docs/phase-9g-g-pre-plan.md §6）
    //   - 嚴格 pre-filter：array only + title non-empty + url non-empty
    //   - item @type 固定 WebPage；只輸出 @type / name / url 三欄位
    //   - 不映射 platform / kind / description / order / target / rel
    //   - 不臆造 specific subType（VideoObject / Book / Periodical 等）
    //   - 與 build-blogger.js buildBloggerJsonLd() 兩端 mirror
    const mentionsItems = [
      ...(Array.isArray(post.relatedLinks) ? post.relatedLinks : []),
      ...(Array.isArray(post.otherLinks) ? post.otherLinks : []),
    ]
      .filter(
        (entry) =>
          entry &&
          typeof entry === 'object' &&
          !Array.isArray(entry) &&
          typeof entry.title === 'string' &&
          entry.title.trim() !== '' &&
          typeof entry.url === 'string' &&
          entry.url.trim() !== '',
      )
      .map((entry) => ({ '@type': 'WebPage', name: entry.title, url: entry.url }));
    const bookMainEntity = buildBookMainEntity(post);
    seo.jsonLd = {
      '@context': 'https://schema.org',
      '@type': 'BlogPosting',
      '@id': canonicalUrl,
      headline: post.title,
      description: post.description || settings.site.description,
      datePublished: post.date,
      dateModified: post.updated || post.date,
      author: { '@type': 'Person', name: post.author || settings.site.author },
      mainEntityOfPage: canonicalUrl,
      inLanguage: settings.site.language,
      articleSection: findCategoryName(settings, post.category),
      isPartOf: {
        '@type': 'Blog',
        '@id': blogSiteUrl,
        name: settings.site.siteName,
        url: blogSiteUrl,
        inLanguage: settings.site.language,
      },
      ...(mentionsItems.length > 0 ? { mentions: mentionsItems } : {}),
      ...(bookMainEntity ? { mainEntity: bookMainEntity } : {}),
    };
    if (ogImage) seo.jsonLd.image = ogImage;
  }
  return seo;
}

function buildSeoForCategory({ settings, group }) {
  const slug = group.category?.slug || group.category?.id;
  const canonicalUrl = buildCanonicalUrl({ pageType: 'category', settings, slug });
  return commonSeo({ pageType: 'category', settings, canonicalUrl });
}

function buildSeoForCategoryList({ settings }) {
  const canonicalUrl = buildCanonicalUrl({ pageType: 'category-list', settings });
  return commonSeo({ pageType: 'category-list', settings, canonicalUrl });
}

function buildSeoForTag({ settings, group }) {
  const slug = group.tag?.slug || group.tag?.id;
  const canonicalUrl = buildCanonicalUrl({ pageType: 'tag', settings, slug });
  return commonSeo({ pageType: 'tag', settings, canonicalUrl });
}

function buildSeoForTagList({ settings }) {
  const canonicalUrl = buildCanonicalUrl({ pageType: 'tag-list', settings });
  return commonSeo({ pageType: 'tag-list', settings, canonicalUrl });
}

// Phase related-links-ga4-audit：對 relatedLinks / otherLinks 預處理。
//   - 對 Blogger cross-link 連結注入 UTM + 設 target=_blank + 合併 rel（per ga4-url-builder.applyCrossSiteUtm）
//   - 非 Blogger 連結維持原樣（item.target / item.rel 為 null；EJS template 走 fallback 既有邏輯）
//   - 非 object / 非 string url 之 item 維持原樣（EJS render-time filter 會 skip）
function deriveRenderedCrossLinks(rawLinks, settings, slot) {
  const arr = Array.isArray(rawLinks) ? rawLinks : [];
  return arr.map((item) => {
    if (!item || typeof item !== 'object' || Array.isArray(item)) return item;
    if (typeof item.url !== 'string' || item.url.trim() === '') return item;
    const xs = applyCrossSiteUtm({
      url: item.url,
      settings,
      slot,
      existingRel: typeof item.rel === 'string' ? item.rel : '',
    });
    if (xs.target === null) return item; // 非 Blogger cross-link：不動
    return { ...item, url: xs.url, target: xs.target, rel: xs.rel };
  });
}

function buildSeoNoindex({ pageType, settings }) {
  return {
    ...commonSeo({ pageType, settings, canonicalUrl: null }),
    robots: 'noindex, nofollow',
  };
}

async function main() {
  const mode = parseMode(process.argv.slice(2));
  const startedAt = new Date();
  const outputs = [];

  // Phase Admin-1-b：每次 run 都清除 .cache/pages/admin/ 殘留；dev-mode 之後會 re-create
  //   - 防止 prod build 因 stale .cache 而把 admin/index.html 帶進 dist/
  //   - 即使 vite emptyOutDir 清 dist，.cache 不被清，故需 build-github.js 主動處理
  const adminCacheDir = path.join(PAGES_DIR, 'admin');
  await fs.rm(adminCacheDir, { recursive: true, force: true }).catch(() => {});

  const settings = await loadSettings();
  // Phase 8-f-2-b：plumbing — settings 經 loadPosts 轉發至 processMarkdownEntry / normalizePostOutput
  // Phase 9-i-f-b：改用 loadGithubPosts() cross-source aggregator；mirror loadBloggerPosts 既有模式
  //   含 github 原生 source + content/blogger/posts 中 publishTargets.github.enabled === true 之 cross-source
  const githubPosts = await loadGithubPosts({ settings });
  const baseData = makeBaseData(settings);

  const { warnings } = validateContent({ posts: githubPosts.posts, settings });

  const postsOutput = {
    buildAt: startedAt.toISOString(),
    mode,
    site: 'github',
    siteName: settings.site.siteName,
    totalScanned: githubPosts.totalScanned,
    totalReady: githubPosts.totalReady,
    totalFiltered: githubPosts.totalFiltered,
    posts: githubPosts.posts,
    filteredOut: githubPosts.filteredOut,
  };
  await writeJson(path.join(DATA_DIR, 'posts.json'), postsOutput, outputs);
  await writeJson(path.join(DATA_DIR, 'site.json'), settings, outputs);

  await writeText(path.join(ASSETS_DIR, 'entry.js'), ENTRY_JS, outputs);

  const homeHtml = await renderPage({
    template: 'pages/home.ejs',
    data: baseData({
      posts: githubPosts.posts,
      title: settings.site.siteName,
      description: settings.site.description,
      seo: buildSeoForHome({ settings }),
    }),
  });
  await writeText(path.join(PAGES_DIR, 'index.html'), homeHtml, outputs);

  const listHtml = await renderPage({
    template: 'pages/post-list.ejs',
    data: baseData({
      posts: githubPosts.posts,
      title: `文章列表 | ${settings.site.siteName}`,
      description: `${settings.site.siteName} 文章列表`,
      seo: buildSeoForPostList({ settings }),
    }),
  });
  await writeText(path.join(PAGES_DIR, 'posts', 'index.html'), listHtml, outputs);

  for (const post of githubPosts.posts) {
    const bodyHtml = renderBody(post.body || '');
    // Phase related-links-ga4-audit：對每篇 post 預處理 relatedLinks / otherLinks
    //   - 對 Blogger cross-link 注入 GA4 UTM + 強制 target=_blank + 合併 rel
    //   - 非 Blogger 連結 / 同站連結維持 EJS 預設邏輯（item.target / item.rel 為 null）
    //   - 既有 utm_* 套用策略 A：跳過 UTM 注入但仍套 target/rel
    const relatedLinksRendered = deriveRenderedCrossLinks(post.relatedLinks, settings, 'related_links');
    const otherLinksRendered = deriveRenderedCrossLinks(post.otherLinks, settings, 'other_links');
    const detailHtml = await renderPage({
      template: 'pages/post-detail.ejs',
      data: baseData({
        post,
        // Phase 8-d-3a：additive alias for EJS ergonomics；指向 8-d-2 掛載之 post.normalized。
        //   - 不重新呼叫 normalizePostOutput；不啟用 deriveGithubUrl；不預測 Blogger URL
        //   - EJS template 本批不改讀 normalized；屬 8-d-3b 之後範圍
        //   - 既有 EJS 仍讀 post.X；本欄位 additive，不影響輸出
        normalized: post.normalized,
        bodyHtml,
        title: `${post.title} | ${settings.site.siteName}`,
        description: post.description || settings.site.description,
        seo: buildSeoForPostDetail({ settings, post }),
        relatedLinksRendered,
        otherLinksRendered,
      }),
    });
    await writeText(path.join(PAGES_DIR, 'posts', post.slug, 'index.html'), detailHtml, outputs);
  }

  const findCategory = (ref) =>
    settings.categories.find((c) => c.id === ref) ||
    settings.categories.find((c) => c.slug === ref) ||
    null;
  const findTag = (ref) =>
    settings.tags.find((t) => t.id === ref) ||
    settings.tags.find((t) => t.slug === ref) ||
    null;

  const categoryMap = new Map();
  for (const post of githubPosts.posts) {
    if (!post.category) continue;
    const cat = findCategory(post.category);
    if (!cat) continue;
    if (!categoryMap.has(cat.slug)) categoryMap.set(cat.slug, { category: cat, posts: [] });
    categoryMap.get(cat.slug).posts.push(post);
  }
  for (const [slug, group] of categoryMap) {
    const html = await renderPage({
      template: 'pages/category.ejs',
      data: baseData({
        category: group.category,
        posts: group.posts,
        title: `分類：${group.category.name} | ${settings.site.siteName}`,
        description: `${settings.site.siteName} 分類「${group.category.name}」文章列表`,
        seo: buildSeoForCategory({ settings, group }),
      }),
    });
    await writeText(path.join(PAGES_DIR, 'categories', slug, 'index.html'), html, outputs);
  }

  const categoryEntries = [];
  for (const cat of settings.categories) {
    const group = categoryMap.get(cat.slug);
    if (group && group.posts.length > 0) {
      categoryEntries.push({ slug: cat.slug, name: cat.name, count: group.posts.length });
    }
  }
  const categoryListHtml = await renderPage({
    template: 'pages/category-list.ejs',
    data: baseData({
      entries: categoryEntries,
      title: `分類索引 | ${settings.site.siteName}`,
      description: `${settings.site.siteName} 分類索引`,
      seo: buildSeoForCategoryList({ settings }),
    }),
  });
  await writeText(path.join(PAGES_DIR, 'categories', 'index.html'), categoryListHtml, outputs);

  const tagMap = new Map();
  for (const post of githubPosts.posts) {
    for (const ref of post.tags || []) {
      const t = findTag(ref);
      if (!t) continue;
      if (!tagMap.has(t.slug)) tagMap.set(t.slug, { tag: t, posts: [] });
      tagMap.get(t.slug).posts.push(post);
    }
  }
  for (const [slug, group] of tagMap) {
    const html = await renderPage({
      template: 'pages/tag.ejs',
      data: baseData({
        tag: group.tag,
        posts: group.posts,
        title: `標籤：${group.tag.name} | ${settings.site.siteName}`,
        description: `${settings.site.siteName} 標籤「${group.tag.name}」文章列表`,
        seo: buildSeoForTag({ settings, group }),
      }),
    });
    await writeText(path.join(PAGES_DIR, 'tags', slug, 'index.html'), html, outputs);
  }

  const tagEntries = [];
  for (const tag of settings.tags) {
    const group = tagMap.get(tag.slug);
    if (group && group.posts.length > 0) {
      tagEntries.push({ slug: tag.slug, name: tag.name, count: group.posts.length });
    }
  }
  const tagListHtml = await renderPage({
    template: 'pages/tag-list.ejs',
    data: baseData({
      entries: tagEntries,
      title: `標籤索引 | ${settings.site.siteName}`,
      description: `${settings.site.siteName} 標籤索引`,
      seo: buildSeoForTagList({ settings }),
    }),
  });
  await writeText(path.join(PAGES_DIR, 'tags', 'index.html'), tagListHtml, outputs);

  const notFoundHtml = await renderPage({
    template: 'pages/404.ejs',
    data: baseData({
      title: `找不到頁面 | ${settings.site.siteName}`,
      description: '找不到頁面',
      seo: buildSeoNoindex({ pageType: '404', settings }),
    }),
  });
  await writeText(path.join(PAGES_DIR, '404.html'), notFoundHtml, outputs);

  const designSubpages = [
    { slug: 'colors', name: 'Colors', code: 'G-02' },
    { slug: 'spacing', name: 'Spacing', code: 'G-03' },
    { slug: 'typography', name: 'Typography', code: 'G-04' },
    { slug: 'buttons', name: 'Buttons', code: 'G-05' },
    { slug: 'cards', name: 'Cards', code: 'G-06' },
    { slug: 'article-components', name: 'Article Components', code: 'G-07' },
  ];

  const designSystemHtml = await renderPage({
    template: 'design-system/index.ejs',
    data: baseData({
      title: `Design System | ${settings.site.siteName}`,
      description: `${settings.site.siteName} Design System`,
      subpages: designSubpages,
      seo: buildSeoNoindex({ pageType: 'design-system', settings }),
    }),
  });
  await writeText(path.join(PAGES_DIR, 'design-system', 'index.html'), designSystemHtml, outputs);

  for (const sub of designSubpages) {
    const html = await renderPage({
      template: `design-system/${sub.slug}.ejs`,
      data: baseData({
        title: `${sub.code} ${sub.name} | Design System | ${settings.site.siteName}`,
        description: `${settings.site.siteName} Design System - ${sub.name}`,
        seo: buildSeoNoindex({ pageType: 'design-system', settings }),
      }),
    });
    await writeText(path.join(PAGES_DIR, 'design-system', sub.slug, 'index.html'), html, outputs);
  }

  // Phase Admin-1-b：dev-mode-only read-only Admin page
  //   - 僅 mode === 'dev' 時 render；prod build 不產出（per admin-local-boundary §3 + admin-1-readonly-preflight Plan B）
  //   - 直接 ejs.renderFile 不 wrap base.ejs（admin 為 standalone HTML；無 nav / GA4 / Ads）
  //   - 寫入 .cache/pages/admin/index.html → vite dev serve 於 /admin/
  //   - 不進 sitemap（build-sitemap.js 不掃 admin）；不進 deploy（cp dist 時無此目錄；prod build 已早 rm）
  if (mode === 'dev') {
    const adminData = await loadAdminPosts({ settings });
    const adminHtml = await ejs.renderFile(
      path.join(VIEWS_DIR, 'admin', 'index.ejs'),
      { posts: adminData.posts, builtAt: startedAt.toISOString() },
      { async: true },
    );
    await writeText(path.join(PAGES_DIR, 'admin', 'index.html'), adminHtml, outputs);
    console.log(`[build-github] admin (dev-mode) rendered: ${adminData.posts.length} posts`);
  }

  const manifest = {
    buildAt: startedAt.toISOString(),
    mode,
    site: 'github',
    totals: {
      scanned: githubPosts.totalScanned,
      ready: githubPosts.totalReady,
      filtered: githubPosts.totalFiltered,
      categoryPages: categoryMap.size,
      tagPages: tagMap.size,
    },
    validate: { warnings: warnings.length },
    outputs: [...outputs, rel(path.join(DATA_DIR, 'build-manifest.json'))],
  };
  await writeJson(path.join(DATA_DIR, 'build-manifest.json'), manifest);

  const elapsed = Date.now() - startedAt.getTime();
  console.log(`[build-github] mode=${mode}`);
  console.log(`[build-github] scanned ${postsOutput.totalScanned}, ready ${postsOutput.totalReady}, filtered ${postsOutput.totalFiltered}`);
  if (postsOutput.filteredOut.length > 0) {
    for (const f of postsOutput.filteredOut) {
      console.log(`[build-github]   filtered: ${f.sourcePath} (${f.reason})`);
    }
  }
  printWarnings(warnings);
  for (const o of manifest.outputs) {
    console.log(`[build-github] wrote ${o}`);
  }
  console.log(`[build-github] done in ${elapsed}ms`);
}

main().catch((err) => {
  console.error('[build-github] failed:', err);
  process.exit(1);
});
