#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ejs from 'ejs';

import { loadSettings } from './load-settings.js';
import { loadPosts } from './load-posts.js';
import { renderBody } from './parse-markdown.js';
import { validateContent, printWarnings } from './validate-content.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..', '..');
const VIEWS_DIR = path.join(PROJECT_ROOT, 'src', 'views');
const CACHE_DIR = path.join(PROJECT_ROOT, '.cache');
const DATA_DIR = path.join(CACHE_DIR, 'data');
const PAGES_DIR = path.join(CACHE_DIR, 'pages');
const ASSETS_DIR = path.join(PAGES_DIR, '_assets');

const ENTRY_JS = `// generated by build-github.js
import '../../../src/js/main.js';
`;

function parseMode(argv) {
  const flag = argv.find((a) => a.startsWith('--mode='));
  if (!flag) return 'dev';
  return flag.split('=')[1] || 'dev';
}

const rel = (p) => path.relative(PROJECT_ROOT, p).split(path.sep).join('/');

async function writeJson(file, data, outputs) {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, JSON.stringify(data, null, 2), 'utf-8');
  if (outputs) outputs.push(rel(file));
}

async function writeText(file, content, outputs) {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, content, 'utf-8');
  if (outputs) outputs.push(rel(file));
}

async function renderPage({ template, data }) {
  const inner = await ejs.renderFile(path.join(VIEWS_DIR, template), data, { async: true });
  const wrapped = await ejs.renderFile(
    path.join(VIEWS_DIR, 'layout', 'base.ejs'),
    { ...data, body: inner },
    { async: true },
  );
  return wrapped;
}

function makeBaseData(settings) {
  return (extra) => ({
    site: settings.site,
    navigation: settings.navigation,
    ...extra,
  });
}

async function main() {
  const mode = parseMode(process.argv.slice(2));
  const startedAt = new Date();
  const outputs = [];

  const settings = await loadSettings();
  const githubPosts = await loadPosts({ site: 'github' });
  const baseData = makeBaseData(settings);

  const { warnings } = validateContent({ posts: githubPosts.posts, settings });

  const postsOutput = {
    buildAt: startedAt.toISOString(),
    mode,
    site: 'github',
    siteName: settings.site.siteName,
    totalScanned: githubPosts.totalScanned,
    totalReady: githubPosts.totalReady,
    totalFiltered: githubPosts.totalFiltered,
    posts: githubPosts.posts,
    filteredOut: githubPosts.filteredOut,
  };
  await writeJson(path.join(DATA_DIR, 'posts.json'), postsOutput, outputs);
  await writeJson(path.join(DATA_DIR, 'site.json'), settings, outputs);

  await writeText(path.join(ASSETS_DIR, 'entry.js'), ENTRY_JS, outputs);

  const homeHtml = await renderPage({
    template: 'pages/home.ejs',
    data: baseData({
      posts: githubPosts.posts,
      title: settings.site.siteName,
      description: settings.site.description,
    }),
  });
  await writeText(path.join(PAGES_DIR, 'index.html'), homeHtml, outputs);

  const listHtml = await renderPage({
    template: 'pages/post-list.ejs',
    data: baseData({
      posts: githubPosts.posts,
      title: `文章列表 | ${settings.site.siteName}`,
      description: `${settings.site.siteName} 文章列表`,
    }),
  });
  await writeText(path.join(PAGES_DIR, 'posts', 'index.html'), listHtml, outputs);

  for (const post of githubPosts.posts) {
    const bodyHtml = renderBody(post.body || '');
    const detailHtml = await renderPage({
      template: 'pages/post-detail.ejs',
      data: baseData({
        post,
        bodyHtml,
        title: `${post.title} | ${settings.site.siteName}`,
        description: post.description || settings.site.description,
      }),
    });
    await writeText(path.join(PAGES_DIR, 'posts', post.slug, 'index.html'), detailHtml, outputs);
  }

  const findCategory = (ref) =>
    settings.categories.find((c) => c.id === ref) ||
    settings.categories.find((c) => c.slug === ref) ||
    null;
  const findTag = (ref) =>
    settings.tags.find((t) => t.id === ref) ||
    settings.tags.find((t) => t.slug === ref) ||
    null;

  const categoryMap = new Map();
  for (const post of githubPosts.posts) {
    if (!post.category) continue;
    const cat = findCategory(post.category);
    if (!cat) continue;
    if (!categoryMap.has(cat.slug)) categoryMap.set(cat.slug, { category: cat, posts: [] });
    categoryMap.get(cat.slug).posts.push(post);
  }
  for (const [slug, group] of categoryMap) {
    const html = await renderPage({
      template: 'pages/category.ejs',
      data: baseData({
        category: group.category,
        posts: group.posts,
        title: `分類：${group.category.name} | ${settings.site.siteName}`,
        description: `${settings.site.siteName} 分類「${group.category.name}」文章列表`,
      }),
    });
    await writeText(path.join(PAGES_DIR, 'categories', slug, 'index.html'), html, outputs);
  }

  const categoryEntries = [];
  for (const cat of settings.categories) {
    const group = categoryMap.get(cat.slug);
    if (group && group.posts.length > 0) {
      categoryEntries.push({ slug: cat.slug, name: cat.name, count: group.posts.length });
    }
  }
  const categoryListHtml = await renderPage({
    template: 'pages/category-list.ejs',
    data: baseData({
      entries: categoryEntries,
      title: `分類索引 | ${settings.site.siteName}`,
      description: `${settings.site.siteName} 分類索引`,
    }),
  });
  await writeText(path.join(PAGES_DIR, 'categories', 'index.html'), categoryListHtml, outputs);

  const tagMap = new Map();
  for (const post of githubPosts.posts) {
    for (const ref of post.tags || []) {
      const t = findTag(ref);
      if (!t) continue;
      if (!tagMap.has(t.slug)) tagMap.set(t.slug, { tag: t, posts: [] });
      tagMap.get(t.slug).posts.push(post);
    }
  }
  for (const [slug, group] of tagMap) {
    const html = await renderPage({
      template: 'pages/tag.ejs',
      data: baseData({
        tag: group.tag,
        posts: group.posts,
        title: `標籤：${group.tag.name} | ${settings.site.siteName}`,
        description: `${settings.site.siteName} 標籤「${group.tag.name}」文章列表`,
      }),
    });
    await writeText(path.join(PAGES_DIR, 'tags', slug, 'index.html'), html, outputs);
  }

  const tagEntries = [];
  for (const tag of settings.tags) {
    const group = tagMap.get(tag.slug);
    if (group && group.posts.length > 0) {
      tagEntries.push({ slug: tag.slug, name: tag.name, count: group.posts.length });
    }
  }
  const tagListHtml = await renderPage({
    template: 'pages/tag-list.ejs',
    data: baseData({
      entries: tagEntries,
      title: `標籤索引 | ${settings.site.siteName}`,
      description: `${settings.site.siteName} 標籤索引`,
    }),
  });
  await writeText(path.join(PAGES_DIR, 'tags', 'index.html'), tagListHtml, outputs);

  const notFoundHtml = await renderPage({
    template: 'pages/404.ejs',
    data: baseData({
      title: `找不到頁面 | ${settings.site.siteName}`,
      description: '找不到頁面',
    }),
  });
  await writeText(path.join(PAGES_DIR, '404.html'), notFoundHtml, outputs);

  const designSubpages = [
    { slug: 'colors', name: 'Colors', code: 'G-02' },
    { slug: 'spacing', name: 'Spacing', code: 'G-03' },
    { slug: 'typography', name: 'Typography', code: 'G-04' },
    { slug: 'buttons', name: 'Buttons', code: 'G-05' },
    { slug: 'cards', name: 'Cards', code: 'G-06' },
    { slug: 'article-components', name: 'Article Components', code: 'G-07' },
  ];

  const designSystemHtml = await renderPage({
    template: 'design-system/index.ejs',
    data: baseData({
      title: `Design System | ${settings.site.siteName}`,
      description: `${settings.site.siteName} Design System`,
      subpages: designSubpages,
    }),
  });
  await writeText(path.join(PAGES_DIR, 'design-system', 'index.html'), designSystemHtml, outputs);

  for (const sub of designSubpages) {
    const html = await renderPage({
      template: `design-system/${sub.slug}.ejs`,
      data: baseData({
        title: `${sub.code} ${sub.name} | Design System | ${settings.site.siteName}`,
        description: `${settings.site.siteName} Design System - ${sub.name}`,
      }),
    });
    await writeText(path.join(PAGES_DIR, 'design-system', sub.slug, 'index.html'), html, outputs);
  }

  const manifest = {
    buildAt: startedAt.toISOString(),
    mode,
    site: 'github',
    totals: {
      scanned: githubPosts.totalScanned,
      ready: githubPosts.totalReady,
      filtered: githubPosts.totalFiltered,
      categoryPages: categoryMap.size,
      tagPages: tagMap.size,
    },
    validate: { warnings: warnings.length },
    outputs: [...outputs, rel(path.join(DATA_DIR, 'build-manifest.json'))],
  };
  await writeJson(path.join(DATA_DIR, 'build-manifest.json'), manifest);

  const elapsed = Date.now() - startedAt.getTime();
  console.log(`[build-github] mode=${mode}`);
  console.log(`[build-github] scanned ${postsOutput.totalScanned}, ready ${postsOutput.totalReady}, filtered ${postsOutput.totalFiltered}`);
  if (postsOutput.filteredOut.length > 0) {
    for (const f of postsOutput.filteredOut) {
      console.log(`[build-github]   filtered: ${f.sourcePath} (${f.reason})`);
    }
  }
  printWarnings(warnings);
  for (const o of manifest.outputs) {
    console.log(`[build-github] wrote ${o}`);
  }
  console.log(`[build-github] done in ${elapsed}ms`);
}

main().catch((err) => {
  console.error('[build-github] failed:', err);
  process.exit(1);
});
