#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ejs from 'ejs';

import { loadSettings } from './load-settings.js';
import { loadPosts } from './load-posts.js';
import { renderBody } from './parse-markdown.js';
import { validateContent, printWarnings } from './validate-content.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..', '..');
const VIEWS_DIR = path.join(PROJECT_ROOT, 'src', 'views');
const CACHE_DIR = path.join(PROJECT_ROOT, '.cache');
const DATA_DIR = path.join(CACHE_DIR, 'data');
const PAGES_DIR = path.join(CACHE_DIR, 'pages');
const ASSETS_DIR = path.join(PAGES_DIR, '_assets');

const ENTRY_JS = `// generated by build-github.js
import '../../../src/js/main.js';
`;

function parseMode(argv) {
  const flag = argv.find((a) => a.startsWith('--mode='));
  if (!flag) return 'dev';
  return flag.split('=')[1] || 'dev';
}

const rel = (p) => path.relative(PROJECT_ROOT, p).split(path.sep).join('/');

async function writeJson(file, data, outputs) {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, JSON.stringify(data, null, 2), 'utf-8');
  if (outputs) outputs.push(rel(file));
}

async function writeText(file, content, outputs) {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, content, 'utf-8');
  if (outputs) outputs.push(rel(file));
}

// Phase 5-b：渲染 SEO partials 後 post-process 注入 base.ejs 產出的 HTML 之 head 內。
// 採用 post-process 而非修改 base.ejs，避開未授權檔案修改。
// Phase 5-d：擴充加入 tracking/ga4 partial，邏輯一致。
const HEAD_PARTIALS = [
  { dir: 'seo', name: 'meta-tags' },
  { dir: 'seo', name: 'open-graph' },
  { dir: 'seo', name: 'canonical' },
  { dir: 'seo', name: 'json-ld' },
  { dir: 'tracking', name: 'ga4' },
  { dir: 'ads', name: 'adsense-head' },
];

async function renderHeadPartials(data) {
  const parts = [];
  for (const { dir, name } of HEAD_PARTIALS) {
    const html = await ejs.renderFile(
      path.join(VIEWS_DIR, dir, `${name}.ejs`),
      data,
      { async: true },
    );
    const trimmed = html.trim();
    if (trimmed) parts.push(trimmed);
  }
  return parts.join('\n');
}

async function renderPage({ template, data }) {
  const inner = await ejs.renderFile(path.join(VIEWS_DIR, template), data, { async: true });
  const wrapped = await ejs.renderFile(
    path.join(VIEWS_DIR, 'layout', 'base.ejs'),
    { ...data, body: inner },
    { async: true },
  );
  const headPartials = await renderHeadPartials(data);
  if (!headPartials) return wrapped;
  return wrapped.replace('</head>', `    ${headPartials.replace(/\n/g, '\n    ')}\n  </head>`);
}

function makeBaseData(settings) {
  return (extra) => ({
    site: settings.site,
    navigation: settings.navigation,
    ga4: settings.ga4,
    ads: settings.ads,
    ...extra,
  });
}

// ---- 5-b SEO helpers --------------------------------------------------------

function siteBaseUrl(settings) {
  return (settings.site?.githubSiteUrl || '').replace(/\/+$/, '');
}

function ogLocaleFromLanguage(language) {
  if (language === 'zh-Hant') return 'zh_TW';
  if (language === 'zh-Hans') return 'zh_CN';
  if (language === 'en' || language === 'en-US') return 'en_US';
  return language || null;
}

function absolutizeUrl(url, base) {
  if (!url) return null;
  if (/^https?:\/\//.test(url)) return url;
  if (!base) return null;
  const cleanPath = url.replace(/^\/+/, '');
  return `${base}/${cleanPath}`;
}

function findCategoryName(settings, value) {
  if (!value) return null;
  const list = settings.categories || [];
  const cat = list.find((c) => c.id === value || c.slug === value);
  return cat?.name || value;
}

function buildCanonicalUrl({ pageType, post, slug, settings }) {
  const base = siteBaseUrl(settings);
  if (!base) return null;
  switch (pageType) {
    case 'home':
      return `${base}/`;
    case 'post-list':
      return `${base}/posts/`;
    case 'post-detail': {
      const raw = post?.canonical;
      if (raw && raw !== 'auto' && /^https?:\/\//.test(raw)) return raw;
      return `${base}/posts/${post.slug}/`;
    }
    case 'category-list':
      return `${base}/categories/`;
    case 'category':
      return `${base}/categories/${slug}/`;
    case 'tag-list':
      return `${base}/tags/`;
    case 'tag':
      return `${base}/tags/${slug}/`;
    case '404':
    case 'design-system':
      return null;
    default:
      return null;
  }
}

function commonSeo({ pageType, settings, canonicalUrl }) {
  return {
    pageType,
    canonicalUrl,
    robots: 'index, follow',
    ogType: 'website',
    ogLocale: ogLocaleFromLanguage(settings.site?.language),
    ogImage: null,
    ogImageAlt: null,
    jsonLd: null,
    publishedTime: null,
    modifiedTime: null,
    keywords: null,
  };
}

function buildSeoForHome({ settings }) {
  const canonicalUrl = buildCanonicalUrl({ pageType: 'home', settings });
  const seo = commonSeo({ pageType: 'home', settings, canonicalUrl });
  if (canonicalUrl) {
    seo.jsonLd = {
      '@context': 'https://schema.org',
      '@type': 'WebSite',
      '@id': canonicalUrl,
      name: settings.site.siteName,
      url: canonicalUrl,
      description: settings.site.description,
      inLanguage: settings.site.language,
    };
  }
  return seo;
}

function buildSeoForPostList({ settings }) {
  const canonicalUrl = buildCanonicalUrl({ pageType: 'post-list', settings });
  return commonSeo({ pageType: 'post-list', settings, canonicalUrl });
}

function buildSeoForPostDetail({ settings, post }) {
  const canonicalUrl = buildCanonicalUrl({ pageType: 'post-detail', settings, post });
  const base = siteBaseUrl(settings);
  const ogImage = absolutizeUrl(post.cover, base);
  const seo = {
    ...commonSeo({ pageType: 'post-detail', settings, canonicalUrl }),
    ogType: 'article',
    ogImage,
    ogImageAlt: post.coverAlt || null,
    publishedTime: post.date || null,
    modifiedTime: post.updated || post.date || null,
    keywords: Array.isArray(post.tags) && post.tags.length > 0 ? post.tags : null,
  };
  if (canonicalUrl) {
    seo.jsonLd = {
      '@context': 'https://schema.org',
      '@type': 'BlogPosting',
      '@id': canonicalUrl,
      headline: post.title,
      description: post.description || settings.site.description,
      datePublished: post.date,
      dateModified: post.updated || post.date,
      author: { '@type': 'Person', name: post.author || settings.site.author },
      mainEntityOfPage: canonicalUrl,
      inLanguage: settings.site.language,
      articleSection: findCategoryName(settings, post.category),
    };
    if (ogImage) seo.jsonLd.image = ogImage;
  }
  return seo;
}

function buildSeoForCategory({ settings, group }) {
  const slug = group.category?.slug || group.category?.id;
  const canonicalUrl = buildCanonicalUrl({ pageType: 'category', settings, slug });
  return commonSeo({ pageType: 'category', settings, canonicalUrl });
}

function buildSeoForCategoryList({ settings }) {
  const canonicalUrl = buildCanonicalUrl({ pageType: 'category-list', settings });
  return commonSeo({ pageType: 'category-list', settings, canonicalUrl });
}

function buildSeoForTag({ settings, group }) {
  const slug = group.tag?.slug || group.tag?.id;
  const canonicalUrl = buildCanonicalUrl({ pageType: 'tag', settings, slug });
  return commonSeo({ pageType: 'tag', settings, canonicalUrl });
}

function buildSeoForTagList({ settings }) {
  const canonicalUrl = buildCanonicalUrl({ pageType: 'tag-list', settings });
  return commonSeo({ pageType: 'tag-list', settings, canonicalUrl });
}

function buildSeoNoindex({ pageType, settings }) {
  return {
    ...commonSeo({ pageType, settings, canonicalUrl: null }),
    robots: 'noindex, nofollow',
  };
}

async function main() {
  const mode = parseMode(process.argv.slice(2));
  const startedAt = new Date();
  const outputs = [];

  const settings = await loadSettings();
  // Phase 8-f-2-b：plumbing — settings 經 loadPosts 轉發至 processMarkdownEntry / normalizePostOutput
  const githubPosts = await loadPosts({ site: 'github', settings });
  const baseData = makeBaseData(settings);

  const { warnings } = validateContent({ posts: githubPosts.posts, settings });

  const postsOutput = {
    buildAt: startedAt.toISOString(),
    mode,
    site: 'github',
    siteName: settings.site.siteName,
    totalScanned: githubPosts.totalScanned,
    totalReady: githubPosts.totalReady,
    totalFiltered: githubPosts.totalFiltered,
    posts: githubPosts.posts,
    filteredOut: githubPosts.filteredOut,
  };
  await writeJson(path.join(DATA_DIR, 'posts.json'), postsOutput, outputs);
  await writeJson(path.join(DATA_DIR, 'site.json'), settings, outputs);

  await writeText(path.join(ASSETS_DIR, 'entry.js'), ENTRY_JS, outputs);

  const homeHtml = await renderPage({
    template: 'pages/home.ejs',
    data: baseData({
      posts: githubPosts.posts,
      title: settings.site.siteName,
      description: settings.site.description,
      seo: buildSeoForHome({ settings }),
    }),
  });
  await writeText(path.join(PAGES_DIR, 'index.html'), homeHtml, outputs);

  const listHtml = await renderPage({
    template: 'pages/post-list.ejs',
    data: baseData({
      posts: githubPosts.posts,
      title: `文章列表 | ${settings.site.siteName}`,
      description: `${settings.site.siteName} 文章列表`,
      seo: buildSeoForPostList({ settings }),
    }),
  });
  await writeText(path.join(PAGES_DIR, 'posts', 'index.html'), listHtml, outputs);

  for (const post of githubPosts.posts) {
    const bodyHtml = renderBody(post.body || '');
    const detailHtml = await renderPage({
      template: 'pages/post-detail.ejs',
      data: baseData({
        post,
        // Phase 8-d-3a：additive alias for EJS ergonomics；指向 8-d-2 掛載之 post.normalized。
        //   - 不重新呼叫 normalizePostOutput；不啟用 deriveGithubUrl；不預測 Blogger URL
        //   - EJS template 本批不改讀 normalized；屬 8-d-3b 之後範圍
        //   - 既有 EJS 仍讀 post.X；本欄位 additive，不影響輸出
        normalized: post.normalized,
        bodyHtml,
        title: `${post.title} | ${settings.site.siteName}`,
        description: post.description || settings.site.description,
        seo: buildSeoForPostDetail({ settings, post }),
      }),
    });
    await writeText(path.join(PAGES_DIR, 'posts', post.slug, 'index.html'), detailHtml, outputs);
  }

  const findCategory = (ref) =>
    settings.categories.find((c) => c.id === ref) ||
    settings.categories.find((c) => c.slug === ref) ||
    null;
  const findTag = (ref) =>
    settings.tags.find((t) => t.id === ref) ||
    settings.tags.find((t) => t.slug === ref) ||
    null;

  const categoryMap = new Map();
  for (const post of githubPosts.posts) {
    if (!post.category) continue;
    const cat = findCategory(post.category);
    if (!cat) continue;
    if (!categoryMap.has(cat.slug)) categoryMap.set(cat.slug, { category: cat, posts: [] });
    categoryMap.get(cat.slug).posts.push(post);
  }
  for (const [slug, group] of categoryMap) {
    const html = await renderPage({
      template: 'pages/category.ejs',
      data: baseData({
        category: group.category,
        posts: group.posts,
        title: `分類：${group.category.name} | ${settings.site.siteName}`,
        description: `${settings.site.siteName} 分類「${group.category.name}」文章列表`,
        seo: buildSeoForCategory({ settings, group }),
      }),
    });
    await writeText(path.join(PAGES_DIR, 'categories', slug, 'index.html'), html, outputs);
  }

  const categoryEntries = [];
  for (const cat of settings.categories) {
    const group = categoryMap.get(cat.slug);
    if (group && group.posts.length > 0) {
      categoryEntries.push({ slug: cat.slug, name: cat.name, count: group.posts.length });
    }
  }
  const categoryListHtml = await renderPage({
    template: 'pages/category-list.ejs',
    data: baseData({
      entries: categoryEntries,
      title: `分類索引 | ${settings.site.siteName}`,
      description: `${settings.site.siteName} 分類索引`,
      seo: buildSeoForCategoryList({ settings }),
    }),
  });
  await writeText(path.join(PAGES_DIR, 'categories', 'index.html'), categoryListHtml, outputs);

  const tagMap = new Map();
  for (const post of githubPosts.posts) {
    for (const ref of post.tags || []) {
      const t = findTag(ref);
      if (!t) continue;
      if (!tagMap.has(t.slug)) tagMap.set(t.slug, { tag: t, posts: [] });
      tagMap.get(t.slug).posts.push(post);
    }
  }
  for (const [slug, group] of tagMap) {
    const html = await renderPage({
      template: 'pages/tag.ejs',
      data: baseData({
        tag: group.tag,
        posts: group.posts,
        title: `標籤：${group.tag.name} | ${settings.site.siteName}`,
        description: `${settings.site.siteName} 標籤「${group.tag.name}」文章列表`,
        seo: buildSeoForTag({ settings, group }),
      }),
    });
    await writeText(path.join(PAGES_DIR, 'tags', slug, 'index.html'), html, outputs);
  }

  const tagEntries = [];
  for (const tag of settings.tags) {
    const group = tagMap.get(tag.slug);
    if (group && group.posts.length > 0) {
      tagEntries.push({ slug: tag.slug, name: tag.name, count: group.posts.length });
    }
  }
  const tagListHtml = await renderPage({
    template: 'pages/tag-list.ejs',
    data: baseData({
      entries: tagEntries,
      title: `標籤索引 | ${settings.site.siteName}`,
      description: `${settings.site.siteName} 標籤索引`,
      seo: buildSeoForTagList({ settings }),
    }),
  });
  await writeText(path.join(PAGES_DIR, 'tags', 'index.html'), tagListHtml, outputs);

  const notFoundHtml = await renderPage({
    template: 'pages/404.ejs',
    data: baseData({
      title: `找不到頁面 | ${settings.site.siteName}`,
      description: '找不到頁面',
      seo: buildSeoNoindex({ pageType: '404', settings }),
    }),
  });
  await writeText(path.join(PAGES_DIR, '404.html'), notFoundHtml, outputs);

  const designSubpages = [
    { slug: 'colors', name: 'Colors', code: 'G-02' },
    { slug: 'spacing', name: 'Spacing', code: 'G-03' },
    { slug: 'typography', name: 'Typography', code: 'G-04' },
    { slug: 'buttons', name: 'Buttons', code: 'G-05' },
    { slug: 'cards', name: 'Cards', code: 'G-06' },
    { slug: 'article-components', name: 'Article Components', code: 'G-07' },
  ];

  const designSystemHtml = await renderPage({
    template: 'design-system/index.ejs',
    data: baseData({
      title: `Design System | ${settings.site.siteName}`,
      description: `${settings.site.siteName} Design System`,
      subpages: designSubpages,
      seo: buildSeoNoindex({ pageType: 'design-system', settings }),
    }),
  });
  await writeText(path.join(PAGES_DIR, 'design-system', 'index.html'), designSystemHtml, outputs);

  for (const sub of designSubpages) {
    const html = await renderPage({
      template: `design-system/${sub.slug}.ejs`,
      data: baseData({
        title: `${sub.code} ${sub.name} | Design System | ${settings.site.siteName}`,
        description: `${settings.site.siteName} Design System - ${sub.name}`,
        seo: buildSeoNoindex({ pageType: 'design-system', settings }),
      }),
    });
    await writeText(path.join(PAGES_DIR, 'design-system', sub.slug, 'index.html'), html, outputs);
  }

  const manifest = {
    buildAt: startedAt.toISOString(),
    mode,
    site: 'github',
    totals: {
      scanned: githubPosts.totalScanned,
      ready: githubPosts.totalReady,
      filtered: githubPosts.totalFiltered,
      categoryPages: categoryMap.size,
      tagPages: tagMap.size,
    },
    validate: { warnings: warnings.length },
    outputs: [...outputs, rel(path.join(DATA_DIR, 'build-manifest.json'))],
  };
  await writeJson(path.join(DATA_DIR, 'build-manifest.json'), manifest);

  const elapsed = Date.now() - startedAt.getTime();
  console.log(`[build-github] mode=${mode}`);
  console.log(`[build-github] scanned ${postsOutput.totalScanned}, ready ${postsOutput.totalReady}, filtered ${postsOutput.totalFiltered}`);
  if (postsOutput.filteredOut.length > 0) {
    for (const f of postsOutput.filteredOut) {
      console.log(`[build-github]   filtered: ${f.sourcePath} (${f.reason})`);
    }
  }
  printWarnings(warnings);
  for (const o of manifest.outputs) {
    console.log(`[build-github] wrote ${o}`);
  }
  console.log(`[build-github] done in ${elapsed}ms`);
}

main().catch((err) => {
  console.error('[build-github] failed:', err);
  process.exit(1);
});
